version : '3'

services:
    lb:
        image: haproxy
        ports:
            - "80:80"
        volumes:
            - ./haproxy:/usr/local/etc/haproxy
    nodeapp1:
        image: freelunch
        environment:
            - APPID=1111
    nodeapp2:
        image: freelunch
        environment:
            - APPID=2222
    nodeapp3:
        image: freelunch
        environment:
            - APPID=3333
        